### ISSUE TITLE
[BUG] Fix bot crahes

### ISSUE THREAD

**Issue by TimJentzsch** [TimJentzsch/valveGamesAnnouncerBot#37]
**Describe the bug**
The deployed bot currently crashes for unknown reasons.
It outputs the following error:
```
0|_main  | 2019-04-12 20:29:27 [Updater]         info:   Started updater.
0|_main  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|_main  | StatusCodeError: 400 - {"message":"Bad Request","error":400}
0|_main  |     at new StatusCodeError (/home/zach/projects/valveGamesAnnouncerBot/node_modules/request-promise/lib/errors.js:32:15)
0|_main  |     at Request.RP$callback [as _callback] (/home/zach/projects/valveGamesAnnouncerBot/node_modules/request-promise/lib/rp.js:77:29)
0|_main  |     at Request.self.callback (/home/zach/projects/valveGamesAnnouncerBot/node_modules/request/request.js:185:22)
0|_main  |     at Request.emit (events.js:182:13)
0|_main  |     at Request.<anonymous> (/home/zach/projects/valveGamesAnnouncerBot/node_modules/request/request.js:1161:10)
0|_main  |     at Request.emit (events.js:182:13)
0|_main  |     at IncomingMessage.<anonymous> (/home/zach/projects/valveGamesAnnouncerBot/node_modules/request/request.js:1083:12)
0|_main  |     at Object.onceWrapper (events.js:273:13)
0|_main  |     at IncomingMessage.emit (events.js:187:15)
0|_main  |     at endReadableNT (_stream_readable.js:1094:12)
0|_main  |     at args.(anonymous function) (/home/zach/.config/yarn/global/node_modules/event-loop-inspector/index.js:138:29)
0|_main  |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**To Reproduce**
This issue is still under investigation.

**Expected behavior**
The bot should not crash.

**Comment by zachkont** [comment]
Haven't seen this issue since May 5 when #40 was merged, closing
